export { detectMetadata } from "./core/detect";
export { normalizeMetadata } from "./core/normalize";
export { convertMetadata, parseMetadata, processMetadata, registerParser } from "./core/engine";
export { isStreamMetadataError, readStreamMetadata } from "./transport/icy";
export { resolveMetadata } from "./resolver";
export { assessAirplayEligibility } from "./quality";
export { createAudioFingerprint, getFingerprintCapability, parseFpcalcOutput } from "./recognition";
export type { BuiltInMetadataFormat, CanonicalMetadata, Detection, MetadataFormat, MetadataParser, ParseOptions, ProcessOptions } from "./core/types";
export type { StreamMetadata, StreamMetadataError, StreamMetadataErrorCategory, StreamMetadataOptions, StreamMetadataResult, StreamTransportHeaders } from "./transport/icy";
export type { BuiltInResolutionMethod, NativeDiscoveryOptions, ResolutionAttempt, ResolutionMethod, ResolveMetadataOptions, ResolveMetadataResult, ResolvedMetadata, SidecarSource, UnresolvedMetadata } from "./resolver";
export type { AirplayEligibility, AirplayIneligibilityReason } from "./quality";
export type { AudioFingerprint, AudioFingerprintResult, FingerprintCapability, FingerprintCommandResult, FingerprintCommandRunner, FingerprintError, FingerprintErrorCategory, FingerprintOptions, RecognitionProvider, RecognitionResult } from "./recognition";
